version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    cap_add:
      - SYS_NICE # Desabilitar o aviso "mbind: Operation not permitted"
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - '3308:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=virtex
      
  Php:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1